In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random

In [52]:
# to read in pandas from various format

# loading a data frame
# df = pd.read_csv('data.csv')
# df = pd.read_excel('data.xlsx')
# df = pd.DataFrame(data_dict)     # from dictionary

In [ ]:
df = pd.read_csv("new_clean_imdb.csv")

In [20]:
df.drop(columns=['Unnamed: 0'], inplace=True)

### initial data analysis

In [54]:
df.head()
# df.tail()
# df.sample(5)

,Title,Summary,Director,Writer,Main Genres,Motion Picture Rating,runtime_min,Release Year,rating_outof_10,no_of_rating,Budget,Gross worldwide
0,Napoleon,An epic that details the checkered rise and fa...,Ridley Scott,David Scarpa,"Action,Adventure,Biography",R,158.0,2023.0,7.0,38000.0,NaN,84968381.0
1,The Hunger Games: The Ballad of Songbirds & Sn...,Coriolanus Snow mentors and develops feelings ...,Francis Lawrence,"Michael Lesslie,Michael Arndt,Suzanne Collins","Action,Adventure,Drama",PG-13,157.0,2023.0,2.0,37000.0,100000000.0,191729235.0
2,The Killer,"After a fateful near-miss, an assassin battles...",David Fincher,"Andrew Kevin Walker,Luc Jacamon,Alexis Nolent","Action,Adventure,Crime",R,118.0,2023.0,8.0,117000.0,NaN,421332.0
3,Leo,A 74-year-old lizard named Leo and his turtle ...,"David Wachtenheim,Robert Smigel,Robert Marianetti","Paul Sado,Robert Smigel,Adam Sandler","Animation,Comedy,Family",PG,102.0,2023.0,0.0,10000.0,NaN,NaN
4,Thanksgiving,"After a Black Friday riot ends in tragedy, a m...",Eli Roth,"Eli Roth,Jeff Rendell","Horror,Mystery,Thriller",R,106.0,2023.0,0.0,9100.0,NaN,29666585.0

In [22]:
df.shape

(9083, 12)

In [23]:
df.columns

Index(['Title', 'Summary', 'Director', 'Writer', 'Main Genres',
       'Motion Picture Rating', 'runtime_min', 'Release Year',
       'rating_outof_10', 'no_of_rating', 'Budget', 'Gross worldwide'],
      dtype='object')

In [55]:
df.info()
# df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9083 entries, 0 to 9082
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Title                  9083 non-null   object
 1   Summary                9083 non-null   object
 2   Director               9083 non-null   object
 3   Writer                 9083 non-null   object
 4   Main Genres            9076 non-null   object
 5   Motion Picture Rating  9083 non-null   object
 6   runtime_min            9083 non-null   float64
 7   Release Year           9076 non-null   float64
 8   rating_outof_10        9083 non-null   float64
 9   no_of_rating           8813 non-null   float64
 10  Budget                 5879 non-null   float64
 11  Gross worldwide        7128 non-null   float64
dtypes: float64(6), object(6)
memory usage: 851.7+ KB

In [57]:
# to check for null and duplicated values

df.isna().sum()
df.isnull().sum()

df.duplicated().sum()

# for specific column and rows 
df.loc[1].isna()

Title                    False
Summary                  False
Director                 False
Writer                   False
Main Genres              False
Motion Picture Rating    False
runtime_min              False
Release Year             False
rating_outof_10          False
no_of_rating             False
Budget                   False
Gross worldwide          False
Name: 1, dtype: bool

### loc basics

In [35]:
df.loc[:,'Budget']       # single column 
# loc uses label for tampering with dataframe

0               NaN
1       100000000.0
2               NaN
3               NaN
4               NaN
           ...
9078            NaN
9079      6400000.0
9080      4000000.0
9081            NaN
9082            NaN
Name: Budget, Length: 9083, dtype: float64

In [32]:
df.loc[1] # single row

Title                    The Hunger Games: The Ballad of Songbirds & Sn...
Summary                  Coriolanus Snow mentors and develops feelings ...
Director                                                  Francis Lawrence
Writer                       Michael Lesslie,Michael Arndt,Suzanne Collins
Main Genres                                         Action,Adventure,Drama
Motion Picture Rating                                                PG-13
runtime_min                                                          157.0
Release Year                                                        2023.0
rating_outof_10                                                        2.0
no_of_rating                                                       37000.0
Budget                                                         100000000.0
Gross worldwide                                                191729235.0
Name: 1, dtype: object

In [31]:
df.loc[df.Director == 'Aatish Kapadia', ['runtime_min', 'Release Year', 'Writer', 'Title']]

      runtime_min  Release Year          Writer      Title
2772        121.0        2023.0  Aatish Kapadia  Khichdi 2

In [36]:
# df.loc[row, column]
# can also use slicing, conditional cases for both rows and column but label for column and row must be valid.

### iloc basics

In [37]:
# similar to loc but use index for labeling row and column index starts from 0 onwards

In [ ]:
df.loc[1, :] # works for rows because index is from 0 onwards
# df.loc[:,1]    # doesn't work i.e 1 doesn't correspond to Summary?

0       An epic that details the checkered rise and fa...
1       Coriolanus Snow mentors and develops feelings ...
2       After a fateful near-miss, an assassin battles...
3       A 74-year-old lizard named Leo and his turtle ...
4       After a Black Friday riot ends in tragedy, a m...
                              ...
9078    In this animated musical, a girl builds a rock...
9079    A young drifter working on a river barge disru...
9080    The dramatic lives of trapeze artists, a clown...
9081    A group of international passengers en route f...
9082    A group of men set out in search of a dead bod...
Name: Summary, Length: 9083, dtype: object

In [47]:
df.iloc[1, :]      # works as intended
df.iloc[:, 1]       # works here gives all the title value

0       An epic that details the checkered rise and fa...
1       Coriolanus Snow mentors and develops feelings ...
2       After a fateful near-miss, an assassin battles...
3       A 74-year-old lizard named Leo and his turtle ...
4       After a Black Friday riot ends in tragedy, a m...
                              ...
9078    In this animated musical, a girl builds a rock...
9079    A young drifter working on a river barge disru...
9080    The dramatic lives of trapeze artists, a clown...
9081    A group of international passengers en route f...
9082    A group of men set out in search of a dead bod...
Name: Summary, Length: 9083, dtype: object

In [51]:
df.iloc[[1,2,3], 5:8]

  Motion Picture Rating  runtime_min  Release Year
1                 PG-13        157.0        2023.0
2                     R        118.0        2023.0
3                    PG        102.0        2023.0

In [48]:
# Now similar to loc we can use condtion, slicing to access value form both rows and column but using index

In [66]:
## other ways to access

df[df["Director"].isin(['David Fincher', 'Aatish Kapadia'])]

,Title,Summary,Director,Writer,Main Genres,Motion Picture Rating,runtime_min,release_year,rating_outof_10,no_of_rating,Budget,Gross worldwide
2,The Killer,"After a fateful near-miss, an assassin battles...",David Fincher,"Andrew Kevin Walker,Luc Jacamon,Alexis Nolent","Action,Adventure,Crime",R,118.0,2023.0,8.0,117000.0,NaN,421332.0
283,Alien³,"Returning from LV-426, Ellen Ripley crash-land...",David Fincher,"Dan O'Bannon,Vincent Ward,Ronald Shusett","Action,Horror,Sci-Fi",R,114.0,1992.0,4.0,314000.0,50000000.0,159814498.0
726,Fight Club,An insomniac office worker and a devil-may-car...,David Fincher,"Chuck Palahniuk,Jim Uhls",Drama,R,139.0,1999.0,8.0,2300000.0,63000000.0,101209702.0
1181,Panic Room,A divorced woman and her diabetic daughter tak...,David Fincher,David Koepp,"Crime,Drama,Thriller",R,112.0,2002.0,8.0,292000.0,48000000.0,197079546.0
1257,Se7en,"Two detectives, a rookie and a veteran, hunt a...",David Fincher,Andrew Kevin Walker,"Crime,Drama,Mystery",R,127.0,1995.0,6.0,1800000.0,33000000.0,327333559.0
1266,Gone Girl,With his wife's disappearance having become th...,David Fincher,Unknown,"Drama,Mystery,Thriller",R,149.0,2014.0,1.0,1000000.0,61000000.0,369330363.0
2356,The Social Network,As Harvard student Mark Zuckerberg creates the...,David Fincher,"Ben Mezrich,Aaron Sorkin","Biography,Drama",PG-13,105.0,2010.0,8.0,743000.0,40000000.0,224920375.0
2772,Khichdi 2,Parekh family discovers that the King of Paant...,Aatish Kapadia,Aatish Kapadia,"Adventure,Comedy",Unrated,121.0,2023.0,9.0,243.0,NaN,27989.0
3459,The Girl with the Dragon Tattoo,Journalist Mikael Blomkvist is aided in his se...,David Fincher,"Stieg Larsson,Steven Zaillian","Crime,Drama,Mystery",R,158.0,2011.0,8.0,486000.0,90000000.0,232617430.0
3988,Zodiac,"Between 1968 and 1983, a San Francisco cartoon...",David Fincher,"Robert Graysmith,James Vanderbilt","Crime,Drama,Mystery",R,157.0,2007.0,7.0,582000.0,65000000.0,84785914.0
6687,Mank,1930s Hollywood is re-evaluated through the ey...,David Fincher,Jack Fincher,"Biography,Comedy,Drama",R,131.0,2020.0,8.0,81000.0,NaN,NaN
6691,The Game,After a wealthy San Francisco banker is given ...,David Fincher,"John Brancato,Michael Ferris","Drama,Mystery,Thriller",R,129.0,1997.0,7.0,420000.0,50000000.0,109423648.0
7256,The Curious Case of Benjamin Button,"Tells the story of Benjamin Button, a man who ...",David Fincher,"Robin Swicord,F. Scott Fitzgerald,Eric Roth","Drama,Fantasy,Romance",PG-13,166.0,2008.0,8.0,683000.0,150000000.0,335802786.0

### Rename column title

In [65]:
df.rename(columns={'Release Year': 'release_year'}, inplace=True)

In [ ]:
# df.rename(columns={'old_name': 'new_name'}, inplace=True)

# df['new_name'] = df['old_name'] 
# then drop old name columns using 
# df.drop(columns=[column or list of column], inplace=True)

In [61]:
# df.rename(columns={'sex': 'gender'}, inplace=True)

# df = df.set_axis(['a','b','c',"d",'e','f','g'], axis=1)

In [64]:
# old_name = ['a','b','c',"d",'e','f','g']
# new_name = ['total_bill', 'tip', 'gender', 'smoker', 'day', 'time', 'size']
# df.rename(columns=dict(zip(old_name, new_name)), inplace=True)
# df

### set index remove index, etc...

In [60]:
# df.set_index('column_name', inplace=True)

# if the index gets title 
# df.index.name = None
# or
# df=df.rename_axis(None, axis=1)

In [63]:
# df.reset_index()  # removes index

### unique value

In [68]:
pd.unique(df.Title)[1:6]

array(['The Hunger Games: The Ballad of Songbirds & Snakes', 'The Killer',
       'Leo', 'Thanksgiving', 'Oppenheimer'], dtype=object)

In [78]:
# rows repeated for Director = each unique value

df['Director'].value_counts()

Director
Steven Spielberg    33
Unknown             31
Clint Eastwood      31
Martin Scorsese     29
Ridley Scott        29
                    ..
Gerald Thomas        1
Kerry Bellessa       1
Fernando Trueba      1
Nithish Sahadev      1
Dick Maas            1
Name: count, Length: 4364, dtype: int64

In [72]:
set(df['Title'])

{'Fatal Attraction',
 'Blazing Saddles',
 'One Piece Film: Red',
 'Lincoln',
 'Used Cars',
 'Time Trap',
 'Beast of Burden',
 'King Arthur',
 'The Protector',
 'Munna Bhai M.B.B.S.',
 'A Good Old Fashioned Orgy',
 'Happiness',
 "National Lampoon's Christmas Vacation",
 'I Heart Huckabees',
 'The Babysitter',
 'Street Fighter',
 'Ichi the Killer',
 'Project Artemis',
 'Marlowe',
 'Friends with Benefits',
 '8-Bit Christmas',
 'The Expendables',
 'Dirty Games',
 'Before We Go',
 'The Babadook',
 'World War Z',
 'Men & Chicken',
 'Saw IV',
 'Mission: Impossible - Dead Reckoning Part Two',
 'Just Like Heaven',
 'City of God',
 'Last Call for Istanbul',
 'Bound by Honor',
 'Captain Underpants: The First Epic Movie',
 'The Kill Team',
 'Rat Race',
 'The Sacrifice Game',
 'Nuovo Olimpo',
 'Cut Bank',
 'Boy',
 'Taxi',
 'The Witcher: Nightmare of the Wolf',
 'The Last Kingdom: Seven Kings Must Die',
 'High Life',
 'Kama Sutra: A Tale of Love',
 'I Spit on Your Grave: Vengeance Is Mine',
 'Love & Mercy',
 '2067',
 'Hidden',
 'The Beach',
 'Arlington Road',
 'The Big Bird Cage',
 'Minecraft',
 'Cold War',
 'The General',
 'Heathers',
 "Devil's Knot",
 'Forbidden Planet',
 'Modern Times',
 'Maybe I Do',
 'The Girl with All the Gifts',
 'Christmas with the Kranks',
 'Silenced',
 'Hell House LLC II: The Abaddon Hotel',
 '99 Homes',
 'Gloria',
 'Click',
 'Beautiful Beings',
 'Down by Law',
 'Saltburn',
 'A.I. Artificial Intelligence',
 'The Long Goodbye',
 'Asterix and Obelix vs. Caesar',
 'The Red Sea Diving Resort',
 'Meet the Parents',
 'Battlestar Galactica',
 'Once Upon a Time in Venice',
 'Girls on Film',
 'The Odessa File',
 'The Final Destination',
 'Jungle',
 'Spawn',
 'Oliver!',
 'Automata',
 'Zookeeper',
 'Home on the Range',
 'Rock Star',
 'Into the Forest',
 'Phoenix',
 'The Apartment',
 'Airborne',
 'Swingers',
 'Man on the Moon',
 'Following',
 'Manos: The Hands of Fate',
 'Fist Fight',
 'Oslo, August 31st',
 'Nikita',
 'Capernaum',
 'Fired Up!',
 'The Gangster, the Cop, the Devil',
 'Cassandro',
 'Ruby Gillman: Teenage Kraken',
 'A Secret Promise',
 "Can't Buy Me Love",
 'Ice Age',
 'Private Parts',
 'The Shining',
 'Atlantis: The Lost Empire',
 'War Machine',
 'An Awkward Sexual Adventure',
 'Jersey Girl',
 'The Car',
 'The Strays',
 'Our Kind of Traitor',
 'War Sailor',
 'Red Dot',
 'The Venture Bros.: Radiant Is the Blood of the Baboon Heart',
 'Drumline',
 'Wonder Woman',
 'In the Loop',
 'The Missouri Breaks',
 'The Wild Geese',
 'The Tragedy of Macbeth',
 'Village of the Damned',
 'The Devil Conspiracy',
 'Body Double',
 'Black Water',
 'Incendies',
 'Holiday Harmony',
 "The Teachers' Lounge",
 "While We're Young",
 'Free Fire',
 'Friend of the Family',
 'The Fog',
 'Compliance',
 'Going Overboard',
 'Twisters',
 'John Wick: Chapter 2',
 'Plane',
 'The Crush',
 'Heavenly Creatures',
 'Revolutionary Road',
 'Jeepers Creepers',
 'Sherlock Holmes',
 'Walk of Shame',
 'Intruders',
 'Evangelion: 3.0+1.01 Thrice Upon a Time',
 'A Goofy Movie',
 'Nutty Professor II: The Klumps',
 'Little Women',
 'Flightplan',
 'The Battle of Algiers',
 'Kane',
 'The Bronze',
 'Genius',
 'Stan Helsing',
 'Election',
 'Totem',
 'The Awakening',
 "The Devil's Brigade",
 'The Two Jakes',
 'Christmas on the Square',
 'Bell Book and Candle',
 'Lord of War',
 'The Long Kiss Goodnight',
 'Walk the Line',
 'More Dead Than Alive',
 'Tropic Thunder',
 'Spider-Man',
 'Ice Age: Collision Course',
 'Nosferatu',
 'Crank',
 'My Name Is Nobody',
 'Bad Luck Banging or Loony Porn',
 'Party Girl',
 'The Imitation Game',
 'Sex and Lucía',
 'Slaughterhouse-Five',
 'Battleship',
 'Tully',
 'Hannah and Her Sisters',
 'The Experiment',
 "Get Rich or Die Tryin'",
 'Three Steps Above Heaven',
 'MacGruber',
 'Fair Game',
 'Unbroken',
 'Lone Star',
 'The Girl Who Escaped: The Kara Robinson Story',
 'Country Strong',
 'A California Christmas',
 'The Glass House',
 'The Blues Brothers',
 '9',
 '1984',
 'Mystery, Alaska',
 'Hulk',
 'Gold Brick',
 'When It Melts',
 'Arjun Reddy',
 'The Bravados',
 'Proof of Life',
 'The Last Rifleman',
 'Cloverfield',
 'Timecop',
 'Burning Days',
 'Fighting with My Family',
 'The Duke of Burgundy',
 'The Birdcage',
 'Tiger, Blood in the Mouth',
 'Aguirre, the Wrath of God',
 'Yentl',
 'Drive Angry',
 'The Fast Lady',
 'The Purge',
 'Westworld',
 'Another Earth',
 'American Gigolo',
 'The Brady Bunch Movie',
 'McCabe & Mrs. Miller',
 'Greyhound',
 'Mechanic: Resurrection',
 'Office Space',
 'Cooties',
 'Symbol',
 'Amateur Teens',
 'Fighter',
 'Flubber',
 'Theater of Blood',
 'The Prince of Egypt',
 'My Bloody Valentine',
 "A Tourist's Guide to Love",
 'Scrapper',
 'Vindicta',
 'The Last Seduction',
 'UFO',
 'Birth/Rebirth',
 'Revenge of the Nerds II: Nerds in Paradise',
 'Lovelace',
 'I, Tonya',
 'The Railway Man',
 'Asterix & Obelix: Mission Cleopatra',
 'Red Rocket',
 'The Way Way Back',
 'Wall Street',
 "Things to Do in Denver When You're Dead",
 'Barbed Wire Dolls',
 'Spectre',
 'Love Actually',
 'Marry My Dead Body',
 'Nightbreed',
 "The Matchmaker's Playbook",
 'Kodachrome',
 'Angels in the Outfield',
 'Night at the Museum: Secret of the Tomb',
 'Wonder Boys',
 'Sid Is Dead',
 'Spider-Man: Beyond the Spider-Verse',
 'Running Scared',
 'IF',
 'Last Stop Larrimah',
 'The Boy Who Harnessed the Wind',
 'Valley Girl',
 'Minari',
 'From Here to Eternity',
 'The Punisher',
 'Black Crab',
 'Play Misty for Me',
 'Nocturnal Animals',
 'A Most Wanted Man',
 'United 93',
 'The Reader',
 'Meet Cute',
 'The Grand Budapest Hotel',
 'Rumble Fish',
 'Sweet November',
 'Troop Beverly Hills',
 'Anastasia',
 'Blade',
 'Men in Black: International',
 'A Cure for Wellness',
 'Hard Target',
 'Wild Child',
 'Conan the Barbarian',
 'Jason and the Argonauts',
 'Blood Ties',
 'Thelma',
 'Clash of the Titans',
 "Don't Look Away",
 'Poison Ivy II',
 'Palo Alto',
 'Daylight',
 'Miracle on 34th Street',
 'The Truman Show',
 'Adrift',
 'Barber',
 'Contact',
 'Bedazzled',
 'Hayseed',
 'My Little Pony: The Movie',
 'Nightmare Alley',
 'Guardians of the Formula',
 'Batman: The Killing Joke',
 'Rogue One: A Star Wars Story',
 'Goon',
 'The Best Man',
 'Jason X',
 'The Knight Before Christmas',
 'A Perfect Getaway',
 'Indiana Jones and the Dial of Destiny',
 'The A-Team',
 'Double Dragon',
 'Shameless',
 'Wer',
 'Goodnight Mommy',
 'Watchmen',
 'Senior Year',
 'Prom Pact',
 'The Change-Up',
 'Body of Evidence',
 'Oliver Twist',
 'M*A*S*H',
 'From Russia with Love',
 'Cactus Flower',
 'The Witch',
 'The Eternal Daughter',
 'Harry Potter and the Chamber of Secrets',
 'In the Electric Mist',
 'EuroTrip',
 "Flamin' Hot",
 'Blood',
 'Blade Runner',
 'An Officer and a Gentleman',
 'Soulmate',
 "Cirque du Freak: The Vampire's Assistant",
 'The Big Green',
 '3-Iron',
 'The Skeleton Twins',
 'Joe Dirt',
 'Immanence',
 'Lee',
 'The Quake',
 'Starfish',
 'Jumanji',
 'Batman: The Movie',
 'The Philadelphia Experiment',
 'The Devil All the Time',
 'Supercell',
 'Fight Club',
 'Punch-Drunk Love',
 'How It Ends',
 'Pet',
 'Three to Tango',
 'Homefront',
 "Zack Snyder's Justice League",
 'Feast',
 'Real Steel',
 'Young Sherlock Holmes',
 'Quadrophenia',
 'Regression',
 "The Devil's Advocate",
 'House of Sand and Fog',
 'The Lost City',
 "Prizzi's Honor",
 'Beverly Hills Cop',
 'Weekend',
 'Small World',
 'Hyena Road',
 'The Salvation',
 'What Lies Below',
 'Ferry',
 'The Locksmith',
 'They/Them',
 'Blues Brothers 2000',
 'Wild Target',
 'Looking for Her',
 'Nacho Libre',
 'W.E.',
 'Hard to Kill',
 'Night on Earth',
 'Octopussy',
 'Now and Then',
 'The Vault',
 "Dead Man's Hand",
 'The Sisters Brothers',
 'His Only Son',
 'Agora',
 'Summer Lovers',
 'Avalon',
 'Wishmaster',
 'Pixels',
 'The Vanishing',
 'The Leopard',
 'Miranda',
 'Drinking Buddies',
 'Scream 2',
 'Life Itself',
 "All Hallows' Eve",
 'The Cloud-Capped Star',
 'Pretty Woman',
 'Twin Peaks: Fire Walk with Me',
 'Phoenix the Warrior',
 'Terrifier',
 'Laws of Attraction',
 'Prey for the Devil',
 'Maurice',
 'Underwater',
 'eXistenZ',
 "Don't Listen",
 'The Karate Kid',
 'The Omen',
 'Bihter',
 'The Strangers',
 'Sabrina',
 'Hall Pass',
 'Catch-22',
 'The Big Feast',
 'Complete Strangers',
 'Screwballs',
 'Ghost Town',
 'Cross of Iron',
 'Inside Man',
 'Hideaway',
 'Army of Thieves',
 'Unbreakable',
 'Ambulance',
 'Absolutely Anything',
 'In & Out',
 'Till Death',
 'Under the Boardwalk',
 'Nurse',
 'Sardar Udham',
 'Before I Go to Sleep',
 '21',
 'The Family That Preys',
 'Senna',
 'Unthinkable',
 'Johnny & Clyde',
 'Deathstalker',
 'Paint',
 'Palmetto',
 'The Man Who Killed Don Quixote',
 'The Stuff',
 'Midnight in the Garden of Good and Evil',
 'The Delivered',
 'The Collection',
 'In Time',
 'Rocky IV',
 'Death Sentence',
 "It Ain't Over",
 'Lux Æterna',
 'With Honors',
 'Blinded by the Light',
 'Bride Wars',
 'Bait',
 'Napoleon',
 'Beach Babes from Beyond',
 'Here',
 'Knight and Day',
 'Dolittle',
 'Kiss and Kill',
 'Desk Set',
 'Tomb Raider',
 'Some Girls',
 'Life Like',
 'The Inspection',
 'Welcome to Marwen',
 'Babe',
 'Vampire Killers',
 'Infinite',
 'Blank Check',
 'The Swimmers',
 'In the Cut',
 'Not Another Church Movie',
 'Insidious',
 'Return to Silent Hill',
 'Taken 2',
 'Tammy and the T-Rex',
 'Arizona Dream',
 'Bubble Boy',
 'Hiroshima Mon Amour',
 'Awake',
 "Four's a Crowd",
 'Warm Bodies',
 'The Clovehitch Killer',
 'Scoop',
 'Possum',
 'Close to the Horizon',
 'Where the Heart Is',
 'Seems Like Old Times',
 'Repo Man',
 'Head-On',
 'The Hill',
 'Concrete Utopia',
 'Come and See',
 'The Perfect Score',
 'Before I Wake',
 'White Oleander',
 'It Chapter Two',
 'The Saint',
 'One-Eyed Jacks',
 'Countdown',
 'Hell or High Water',
 'Darker Shades of Summer',
 'Pleasure',
 'Hard Candy',
 'Bed Rest',
 'Casino Royale',
 'World Trade Center',
 'Dinner for Schmucks',
 'Horseplay',
 'Instructions Not Included',
 'Red Riding Hood',
 '12 Angry Men',
 'Chompy & The Girls',
 'Lost in Space',
 'Ted',
 'The Weather Man',
 'The Contractor',
 'Moulin Rouge!',
 'Christmas on Mistletoe Farm',
 'Dirty Girl',
 'Y2K',
 'To Have and Have Not',
 'Finestkind',
 'Unpregnant',
 'Royalteen',
 'The Wager: A Tale of Shipwreck, Mutiny, and Murder',
 'The Getaway',
 'Flushed Away',
 'What the Peeper Saw',
 'Bad Boy Bubby',
 'Men in Hope',
 'In the Mouth of Madness',
 'Harry and the Hendersons',
 'Igby Goes Down',
 'High Art',
 'Harakiri',
 'Never Say Never Again',
 'Gridiron Gang',
 'Malena',
 'I Am Dragon',
 'Birdemic: Shock and Terror',
 'Tell It to the Bees',
 'Happy Birthday to Me',
 'You Hurt My Feelings',
 'Castaway',
 'Invasion of the Bee Girls',
 '21 Grams',
 'Gung Ho',
 'We Are What We Are',
 'Curious George',
 'Lords of War',
 'If I Stay',
 '101 Dalmatians',
 'The Incredible Hulk',
 'Unfaithful',
 'Miss Violence',
 'I Want to Eat Your Pancreas',
 'November',
 'Silkwood',
 'Casualties of War',
 'Marfa Girl',
 'Nyad',
 'Enola Holmes',
 'Home Alone 3',
 'Warhorse One',
 'Licence to Kill',
 'The Fall',
 'The Layover',
 'Unicorn Store',
 'Despicable Me 2',
 'Return to Me',
 'Untitled Karate Kid Movie',
 'Regarding Henry',
 '68 Kill',
 'Black Lotus',
 'The Flintstones',
 'The Ballad of Lefty Brown',
 "A Midsummer Night's Dream",
 "Twelve O'Clock High",
 'Trespass Against Us',
 'Simulant',
 'Infinite Storm',
 'Fear Street: Part One - 1994',
 'Strange Magic',
 'The Guernsey Literary and Potato Peel Pie Society',
 'Runaway Train',
 'Final Destination 5',
 'Happiness for Beginners',
 'Sideways',
 'Road to Perdition',
 'House of Tolerance',
 'The Killer',
 'Wet Hot American Summer',
 'Down with Love',
 'Crime Diaries: The Celebrity Stylist',
 'Talk to Me',
 'Transporter 3',
 'Manderlay',
 'The Duchess',
 'Swordfish',
 'Darkest Hour',
 'Good Morning, Vietnam',
 'Brain Damage',
 'Possession',
 'Teen Wolf: The Movie',
 'Flashdance',
 'The Rite',
 'Practical Magic',
 "Charlie's Angels",
 'Men in Black',
 'Project Almanac',
 'Extraction',
 'Waiting for Guffman',
 'Behaving Badly',
 'Hold the Dark',
 'K-PAX',
 'Poltergeist III',
 'Ramona and Beezus',
 'Midnight Express',
 'UHF',
 'Pinball: The Man Who Saved the Game',
 'Cool World',
 'El Topo',
 'The Prince and Me',
 'Beneath the Planet of the Apes',
 'The Seven Year Itch',
 'Beetlejuice',
 'The Last Song',
 'Oldboy',
 'Trainwreck',
 'Cover Girl Killer',
 'Lust for a Vampire',
 'Capricorn One',
 "Pete's Dragon",
 'Under the Tuscan Sun',
 'Rocky Balboa',
 'Zardoz',
 'Tetris',
 'Batman Returns',
 'The Sect',
 'The Good Son',
 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
 'Sumotherhood',
 'The Informer',
 'After Hours',
 'Pontypool',
 'Independence Day',
 'Crawl',
 'Ride or Die',
 'Dead Presidents',
 "They Shoot Horses, Don't They?",
 'The House of Yes',
 'Infernal Affairs',
 'CHIPS',
 'Hudson Hawk',
 'Furiosa: A Mad Max Saga',
 'Kung Fu Panda 3',
 'Steve Jobs',
 'The January Man',
 'Wall Street: Money Never Sleeps',
 'Eugenie',
 'Gingerdead Man vs Evil Bong',
 'The Falling',
 'Spaceballs',
 'Merry Christmas Mr. Lawrence',
 'Sunshine',
 'Häxan',
 '48 Hrs.',
 'Dampyr',
 'Finch',
 'Alien: Covenant',
 'Kuch Kuch Hota Hai',
 'Venom',
 'The Last Starfighter',
 'What Is a Woman?',
 'Hot Shots!',
 'American Beauty',
 'Neon Genesis Evangelion: The End of Evangelion',
 'Over the Hedge',
 'Minamata',
 'Stuber',
 'The Trip',
 'Life as We Know It',
 'Anything for Jackson',
 'Aliens vs. Predator: Requiem',
 'Chopping Mall',
 "Breakin'",
 'The Aristocats',
 'When We First Met',
 'The Advent Calendar',
 'Cocktail',
 'Mortdecai',
 'New Nightmare',
 'Run Hide Fight',
 'The Rebound',
 'Double Lover',
 'Desperados',
 'A Tale of Two Sisters',
 "Smokin' Aces",
 'Lion-Girl',
 'Bad Girls',
 'The Sword and the Sorcerer',
 'Bloody Daddy',
 'Horrorplanet',
 'Stagecoach',
 'Necessary Roughness',
 'Operation Christmas Drop',
 'Ernest Goes to Camp',
 "Love Don't Cost a Thing",
 'The Young Victoria',
 'Boy Erased',
 'Fly Away Home',
 'Tooth Fairy',
 'Skanda: The Attacker',
 'Poltergeist II: The Other Side',
 'Shirley',
 'Curiosa',
 'Togo',
 'Paris, 13th District',
 'Seven Veils',
 'Dick',
 "She's All That",
 'Battle Over Britain',
 'Mischief',
 'Anyone But You',
 'The Wackiest Ship in the Army',
 'True History of the Kelly Gang',
 'Born on the Fourth of July',
 "Bill & Ted's Excellent Adventure",
 'Muppets Most Wanted',
 'Kung Fu Panda 4',
 'Falling for the Manny',
 'Rumble Through the Dark',
 'Piranha 3DD',
 'The Drop',
 'Somewhere in Queens',
 "Film Stars Don't Die in Liverpool",
 'Far from the Madding Crowd',
 'Hit the Road',
 '13',
 'Friday Night Lights',
 'Choose or Die',
 'Baskin',
 'P2',
 'Message Man',
 'We Were Soldiers',
 'Christine',
 'Operation Finale',
 'Zombieland',
 'Knock Knock',
 'San Andreas',
 'Suffragette',
 'Ticket to Paradise',
 'Snow White and the Evil Queen',
 'Murder at Yellowstone City',
 'The Professional',
 'All Quiet on the Western Front',
 'Periodical',
 'Incantation',
 'Survival Island',
 'Grotesque',
 'A Disturbance in the Force',
 'Ski School',
 'Vampire Academy',
 "The Bells of St. Mary's",
 'The Right Stuff',
 'Back to Black',
 'Sound of My Voice',
 '40 Days and 40 Nights',
 'A Savannah Haunting',
 'Big Fat Liar',
 'Beetlejuice 2',
 'Meet the Fockers',
 'Coraline',
 'Some Kind of Beautiful',
 'Uproar',
 'The Wind that Shakes the Barley',
 'Sssssss',
 'The Hills Have Eyes',
 "The Man Who Wasn't There",
 'White Bird',
 "Howl's Moving Castle",
 'Short Term 12',
 'Transformers: Revenge of the Fallen',
 'Santa Claus: The Movie',
 'Revenge',
 'A Christmas Prince: The Royal Wedding',
 'The House That Jack Built',
 'The Ritual',
 'Mona Lisa and the Blood Moon',
 'Wolf Creek',
 'Head',
 'Amityville: The Awakening',
 'Rubber',
 'Parental Guidance',
 '8 Million Ways to Die',
 'Crocodile Dundee',
 'Crypto Boy',
 'It',
 'Thesis',
 'I Spit on Your Grave',
 'We Have Always Lived in the Castle',
 'In the Realm of the Senses',
 'The Prom',
 'Rough Night',
 'Anna and the Apocalypse',
 '2 Days in the Valley',
 'Johnny Mnemonic',
 'Bratz',
 'Superpower',
 'Oppenheimer: The Real Story',
 'Blue Velvet',
 'Mr. Brooks',
 'The Serpent and the Rainbow',
 'Monster Hunter',
 'Now, Voyager',
 'Heaven Can Wait',
 'Diary of a Wimpy Kid: The Long Haul',
 'Femme',
 'I Am Love',
 'Star Trek: Insurrection',
 'Liar Liar',
 'Monos',
 'Wish',
 'The Land Before Time',
 'The Cat in the Hat',
 'Rashomon',
 'The Unforgivable',
 'Anon',
 'Ouija',
 'Hitman: Agent 47',
 'Tootsie',
 'Every Secret Thing',
 'Benedetta',
 'Tell No One',
 'Die in a Gunfight',
 'Monster House',
 'Memories',
 'Spider-Man: Across the Spider-Verse',
 'This Is Spinal Tap',
 'Boon',
 "Class of Nuke 'Em High",
 'She Came from the Woods',
 'The Age of Innocence',
 'Horton Hears a Who!',
 'The Last Manhunt',
 'Stay',
 'Laal Singh Chaddha',
 'San Francisco',
 'Philadelphia',
 'Nashville',
 'Butt Boy',
 'The Inbetweeners',
 'Mary Magdalene',
 'The Portrait',
 'Queer',
 'Ghosted',
 'Black Panther: Wakanda Forever',
 'Plus One',
 'No Time to Die',
 'A Love Song for Bobby Long',
 'Multiplicity',
 'This Is England',
 'At Close Range',
 'The Good Girl',
 'Athena',
 'The Shootist',
 'Planet 51',
 'Hot Dog... The Movie',
 'Scanners',
 'Firefox',
 'Three Men and a Baby',
 'Viking Wolf',
 'To Catch a Thief',
 'The Frighteners',
 'The Longest Day',
 'The Way of the Dragon',
 'Paranormal Activity: Next of Kin',
 'The To Do List',
 'Friends and Strangers',
 'Creature from the Black Lagoon',
 'Amsterdam',
 'Hamilton',
 'National Velvet',
 'Of Love and Shadows',
 'The Longest Yard',
 'Apocalypse Clown',
 'Oblivion',
 'Vendetta',
 'Nathalie...',
 'Upside Down',
 'The Last Witch Hunter',
 'Where the Crawdads Sing',
 'Little Nicky',
 'Tadpole',
 'I Feel Pretty',
 'Terminator: Dark Fate',
 'Silent House',
 'On Deadly Ground',
 'Tesla',
 'The Electrical Life of Louis Wain',
 'Stepmom',
 'Mighty Aphrodite',
 'Dear David',
 'Star Wars: Episode III - Revenge of the Sith',
 'Mad Max: The Wasteland',
 'The Hunger Games: Mockingjay - Part 2',
 'Totally Killer',
 'The Pink Panther',
 "Don't Look Up",
 'The Perfect Find',
 'Audition',
 'The Muppets Take Manhattan',
 'Contagion',
 'Dogma',
 'Ghost Rider: Spirit of Vengeance',
 'John Dies at the End',
 'Breakdown',
 'Die Hard 2',
 'Movie 43',
 'Identity Thief',
 'Aliens',
 'The Concubine',
 'Genie',
 'The Wood',
 'Sniper: G.R.I.T. - Global Response & Intelligence Team',
 'We Are the Flesh',
 'The Call of the Wild',
 'Stuck in Love.',
 'A Bigger Splash',
 'The Hot Chick',
 'Magic Mike XXL',
 'To the Bone',
 "Gerald's Game",
 'Monte Carlo',
 'The King of Comedy',
 'Drive',
 'Last Man Standing',
 'Grand Prix',
 'Violent Night',
 'Stir of Echoes',
 'Point of No Return',
 'Sly',
 'Blood and Bone',
 'Les Misérables',
 'Father of the Bride',
 'Little Dixie',
 'Pillow Talk',
 'Elvis',
 'Resident Evil: Death Island',
 'The Transporter',
 'Heartburn',
 'Letters to Juliet',
 'A Haunted House',
 'Testament of Youth',
 'Dr. Giggles',
 'The Way of the Gun',
 'Bajirao Mastani',
 'Shotgun Wedding',
 'Southbound',
 "Something from Tiffany's",
 'Babe: Pig in the City',
 'Heartbreak Ridge',
 'Loveless',
 'End of Days',
 'No Exit',
 '10 to Midnight',
 'The Curious Case of Benjamin Button',
 'A Christmas Story',
 'I Am Mother',
 'The Water Diviner',
 'Robin Hood: Prince of Thieves',
 "The Bishop's Wife",
 'Lost in the Night',
 'Captain America: Brave New World',
 'Emanuelle, Queen of Sados',
 'Goodfellas',
 'Rookie of the Year',
 'The Man from Nowhere',
 'Enough Said',
 'Hell House LLC III: Lake of Fire',
 'Labyrinth',
 'House at the End of the Street',
 'Bend It Like Beckham',
 'Playtime',
 'Hostile',
 'The Crucible',
 'The Immaculate Room',
 'Irma la Douce',
 'Forever My Girl',
 'Menace II Society',
 'Saving Private Ryan',
 'The Lord of the Rings: The Return of the King',
 'Open Range',
 "Grandma's Boy",
 'Harry Potter and the Half-Blood Prince',
 'Columbus',
 ...}

### to change type of column

In [73]:
# df['old_type'] = df['new_type'].astype(float, int)

In [74]:
# df['name'] = df['name'].str.upper()

In [75]:
# change value of specific item

# df.loc[(df['Title'] == 'something') & (df['Director'] == 'something'), 'column_value_to_change'] = 'new_info_to_add'

### to deal with null values

In [79]:
# to drop row with null value
# df.dropna()

In [80]:
# df.fillna({'column_name': value_to_replace}, inplace=True)

### Notice:
depending the use case for various data the groupby, aggegrate, str.extract, str.replace, etc are mainly useful

### To save file

In [ ]:
# df.to_csv('filename.csv')